# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2263fd4ef10b7e0f21e6498b7c0a06884fe669b3255c0fe7612afd92dae6ee661876e839c54fe40435300fed5dd3945cdf4a579f9966402f9460502c2d5c8d8b

test:
  secret_key_base: dfa7fc9505b60ec4b725dc784726e957846bd20447397f06590fcc9fae00782a6fcf429c181a33400be8fe636db458fda6b6cacaadff3d5669842f589240fea4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
